### ISSUE TITLE
libcxx-16.0.6 macos SDK vs min version 

### ISSUE THREAD

**Issue by mottelet** [conda-forge/libcxx-feedstock#143]
### Comment:

Hello,

I installed conda 23.11.0 on macOS x86_64 and all libraries were build against 10.9 sdk, which is fine as usual, but I saw that  current libcxx-16.0.6 has

Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      **sdk 10.14**

hence no binaries are able to run on old macs having macOS < 10.14 because, for example, std::align_val_t is only available on macOS 10.13 and newer. I have the following issue when running on a macOS 10.9 machine an application compiled against this libc++:
```
dyld: Symbol not found: __ZdaPvSt11align_val_t
  Referenced from: /Applications/scilab-macos_fmemopen.app/Contents/bin/../lib/thirdparty/libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /Applications/scilab-macos_fmemopen.app/Contents/bin/../lib/thirdparty/libc++.1.dylib
```

Why libcxx was not built against 10.9 SDK as other packages ?

I see here : https://github.com/conda-forge/conda-forge.github.io/issues/1844#issuecomment-1467234057 
that libcxx 17 has recently [dropped](https://reviews.llvm.org/D145012) support for macOS<10.13 when building the shared libcxx library (I noted this in https://github.com/conda-forge/libcxx-feedstock/issues/110 when the RFC opened).

but it seems to have been already the same for libcxx 16. 

setting min macOS version to 10.9 is useless if build is made with newer 10.14 SDK (which masks unavailable features in 10.9)

S.

**Comment by h-vetinari** [comment]
Hi!

Please post the information required by the issue template, in particular `conda list` and `conda info`.

Looking at what symbol is missing, we find:
```
>llvm-cxxfilt --strip-underscore __ZdaPvSt11align_val_t
operator delete[](void*, std::align_val_t)
```
so indeed about `std::align_val_t`. That also shows up in this upstream issue https://github.com/llvm/llvm-project/issues/39701, which got solved in https://github.com/llvm/llvm-project/commit/85bdbbf9a12a17a128eadb90644389a276e4e433, and updated in https://github.com/llvm/llvm-project/commit/4722b5d1330a1104a0aa256804b9537c4d2c39d4 (which confirms your claim about support starting from 10.13)

The SDK version should not matter at runtime, for that only the deployment target version should be relevant (i.e. SDK normally only causes. However, I think there _might_ be a libcxx bug that [`libcxx/include/__config`](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/libcxx/include/__config#L735-L745) does not set `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION` on osx<=10.13, because that's what [determines](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/libcxx/include/new#L230) whether that symbol gets defined & used.

(I guess it would also be possible to mark these symbols as unavailable depending on the deployment target in https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/TargetLibraryInfo.cpp, but it seems like libcxx would own this.)

I'm kind of surprised how late in the lifecycle of this package this bug appear - 16.0 has been live in conda-forge for over a year, but the code in hasn't changed for much longer than that. On the other hand, I'm not _that_ surprised because 10.9 has microscopic usage numbers, and I suspect that much of our claimed support has bitrotted away due to being forced to use newer images by Azure Pipelines.

In any case, 10.9 support is basically [dead](https://conda-forge.org/news/2023/08/24/bumping-minimum-macos-version-to-1013/) for a while already (and we're getting close to finally require 10.13), so I'm leaning towards treating this as non-actionable. However, if you want to write a PR targeting the 16.x branch that patches `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION` and has a test, I'm happy to review & merge.

**Comment by mottelet** [comment]
Hello,

Thanks for your reply.

> write a PR targeting the 16.x branch that patches `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION` and has a test, 
 
I am not that experimented with conda recipes, first, please tell me which file in which project I have to patch.

S.

**Comment by h-vetinari** [comment]
You can check out this [branch](https://github.com/h-vetinari/llvm-project/commits/conda_libcxx_16), add your patch for `_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION ` on top, and then do `git format-patches tags/llvmorg-16.0.6 --no-signature`, and add the patches under the [patches](https://github.com/conda-forge/libcxx-feedstock/tree/16.x/recipe/patches) folder as well as here:
https://github.com/conda-forge/libcxx-feedstock/blob/fa1d8373f0add683a1d442bf399b847316004a41/recipe/meta.yaml#L10-L19

Almost arbitrary test scripts can be added under `recipe` and then executed here:
https://github.com/conda-forge/libcxx-feedstock/blob/fa1d8373f0add683a1d442bf399b847316004a41/recipe/meta.yaml#L69
